var menu='\
<h4> Плаваем с маской</h4>\
  <p><a href="star_fish_bright.html"> Яркая звезда</a></p>\
  <p><a href="octopus.html"> Осьминог в норке</a></p>\
  <p><a href="jellyfish.html"> Медуза вблизи</a></p>\
  <p><a href="sky.html"> Вид неба со дна моря</a></p>\
  <p><a href="sea_urchin.html"> Карандашный ёж</a></p>\
  <p><a href="fish-coral-shadow.html"> Рыба-ёж в тени</a></p>\
  <p><a href="christmas-worm-yellow-fire.html"> Рождественский червь</a></p>\
  <p><a href="view.html"> Подводный пейзаж</a></p>\
  <p><a href="cucumber.html"> Морской огурец</a></p>\
  <p><a href="pencil-sea-urchin.html"> Тупые иголки ежа</a></p>\
  <p><a href="sea-cucumber.html"> Голотурия</a></p>\
  <p><a href="christmas_worm_blue.html"> Синий спиробранхус</a></p>\
  <p><a href="christmas_worm_red.html"> Красный спиробранхус</a></p>\
  <p><a href="christmas-worm-yellow-white.html"> Жёлтый спиробранхус</a></p>\
  <p><a href="green-fish-hard-coral.html"> Зелёные рыбки</a></p>\
<h4><a href="coral/index.html"> Разные кораллы</a></h4>\
<h4><a href="../red-sea-fish/index.html"> Рыбы Красного моря</a></h4>';

var menuen='\
<h4> Swimming with mask</h4>\
  <p><a href="christmas-worm-yellow-fire-en.html"> Christmas worm</a></p>\
  <p><a href="star_fish_bright-en.html"> Bright star</a></p>\
  <p><a href="fish-coral-shadow-en.html"> Burrfish in shadow</a></p>\
  <p><a href="view-en.html"> Underwater view</a></p>\
  <p><a href="octopus-en.html"> Octopus in a hole</a></p>\
  <p><a href="jellyfish-en.html"> Jellyfish</a></p>\
  <p><a href="sea-cucumber-en.html"> Holothuria</a></p>\
  <p><a href="sea_urchin-en.html"> Slate-pencil sea urchin</a></p>\
  <p><a href="sky-en.html"> Sky view from the bottom</a></p>\
  <p><a href="christmas_worm_blue-en.html"> Blue worm</a></p>\
  <p><a href="christmas_worm_red-en.html"> Red worm</a></p>\
  <p><a href="christmas-worm-yellow-white-en.html"> Yellow worm</a></p>\
  <p><a href="cucumber-en.html"> Sea cucumber</a></p>\
  <p><a href="green-fish-hard-coral-en.html"> Green fish in coral</a></p>\
  <p><a href="pencil-sea-urchin-en.html"> Pencil sea urchin</a></p>\
<h4><a href="coral/en.html"> Different corals</a></h4>\
<h4><a href="../red-sea-fish/en.html"> Red Sea Fish</a></h4>';