var menu='\
<h4><a href="../index.html"> Рыбы Красного моря</a></h4>\
<h4><a href="index.html"> Рыбы-бабочки</a></h4>\
  <p><a href="royal.html"> Королевская</a></p>\
  <p><a href="diagonal-blue.html"> Сине-полосатая</a></p>\
  <p><a href="face.html"> Смотрит на вас</a></p>\
  <p><a href="blackbacked.html"> Чёрноспинная</a></p>\
  <p><a href="bannerfish-side.html"> Вымпельная</a></p>\
  <p><a href="black_yellow.html"> По диагонали</a></p>\
  <p><a href="chaetodon_fasciatus.html"> Диагональная</a></p>\
  <p><a href="chaetodon-fasciatus-tail.html"> Хвост</a></p>\
  <p><a href="masked.html"> Маскированная</a></p>\
  <p><a href="masked-pair.html"> Парочка</a></p>\
  <p><a href="chaetodon-paucifasciatus.html"> Красноспинная</a></p>';

var menuen='\
<h4><a href="../en.html"> Red Sea Fish</a></h4>\
<h4><a href="en.html"> Butterflyfish</a></h4>\
  <p><a href="royal-en.html"> Royal angelfish</a></p>\
  <p><a href="diagonal-blue-en.html"> Blue-stripes</a></p>\
  <p><a href="chaetodon-paucifasciatus-en.html"> Crown</a></p>\
  <p><a href="blackbacked-en.html"> Blackbacked</a></p>\
  <p><a href="black_yellow-en.html"> Swim diagonally</a></p>\
  <p><a href="chaetodon-fasciatus-tail-en.html"> Yellow tail</a></p>\
  <p><a href="chaetodon_fasciatus-en.html"> Diagonal</a></p>\
  <p><a href="face-en.html"> Banner portrait</a></p>\
  <p><a href="bannerfish-side-en.html"> Bannerfish</a></p>\
  <p><a href="masked-en.html"> Masked</a></p>\
  <p><a href="masked-pair-en.html"> Masked pair</a></p>';