var menu='\
<h4><a href="index.html"> Насекомые</a></h4>\
  <p><a href="hornet.html"> Портрет шершня</a></p>\
  <p><a href="hornet-flying.html"> Полёт шершня</a></p>\
  <p><a href="dragon-with-strips.html"> Стрекоза на травке</a></p>\
  <p><a href="young-ant.html"> Молодой муравей</a></p>\
  <p><a href="grig-maskcolor.html"> Кузнечик маскируется</a></p>\
  <p><a href="dragonfly.html"> Стрекоза на веточке</a></p>\
  <p><a href="green-grasshopper.html"> Кузнечик зелёный</a></p>\
  <p><a href="bee-fly.html"> Муха Сирфида</a></p>\
  <p><a href="bumblebee.html"> Шмель на вишне</a></p>\
  <p><a href="bee-fly-dandelion.html"> Мушка на одуванчике</a></p>\
  <p><a href="two-fly.html"> Пара одиноких мух</a></p>\
  <p><a href="mosquito-enlarged.html"> Увеличенный комар</a></p>\
  <p><a href="fly-hoof.html"> Муха с копытами</a></p>\
  <p><a href="spider-eye.html"> Много глаз паука</a></p>\
  <p><a href="insect-dance.html"> Мошки танцуют</a></p>\
  <p><a href="bombylius-major.html"> Жужжало большое</a></p>\
  <p><a href="centipede.html"> Сколопендра дома</a></p>\
  <p><a href="centipede-hides.html"> Сколопендра прячется</a></p>\
  <p><a href="centipede-sideview.html"> Сколопендра в профиль</a></p>\
  <p><a href="mosquito-net.html"> Комар</a></p>\
<h4><a href="butterfly/index.html"> Бабочки</a></h4>';

var menuen='\
<h4><a href="en.html"> Insect</a></h4>\
  <p><a href="hornet-en.html"> Hornet</a></p>\
  <p><a href="hornet-flying-en.html"> Hornet in flight</a></p>\
  <p><a href="grig-maskcolor-en.html"> Maskcolor</a></p>\
  <p><a href="young-ant-en.html"> An ant on flower</a></p>\
  <p><a href="mosquito-enlarged-en.html"> Mosquito</a></p>\
  <p><a href="bombylius-major-en.html"> Large bee fly</a></p>\
  <p><a href="bee-fly-en.html"> Syrphidae</a></p>\
  <p><a href="spider-eye-en.html"> Eyes of spider</a></p>\
  <p><a href="dragonfly-en.html"> Dragonfly</a></p>\
  <p><a href="centipede-en.html"> House centipede</a></p>\
  <p><a href="fly-hoof-en.html"> Feet of fly</a></p>\
  <p><a href="insect-dance-en.html"> Insect dance</a></p>\
  <p><a href="dragon-with-strips-en.html"> A dragonfly</a></p>\
  <p><a href="bee-fly-dandelion-en.html"> Yellow Syrphida</a></p>\
  <p><a href="bumblebee-en.html"> A bumblebee</a></p>\
  <p><a href="two-fly-en.html"> Two lone flies</a></p>\
  <p><a href="green-grasshopper-en.html"> Grig on fresh grass</a></p>\
  <p><a href="centipede-sideview-en.html"> House centipede</a></p>\
  <p><a href="centipede-hides-en.html"> Centipede hides</a></p>\
  <p><a href="mosquito-net-en.html"> Mosquito</a></p>\
<h4><a href="butterfly/en.html"> Butterflies</a></h4>';